<?xml version="1.0" encoding="UTF-8"?><testrun name="TestModulo" project="BasicProgram" tests="2" started="2" failures="2" errors="0" ignored="0">
  <testsuite name="com.indus.pratice.basics.TestModulo" time="0.002">
    <testcase name="testModuloSer1" classname="com.indus.pratice.basics.TestModulo" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;4.0&gt; but was:&lt;0.0&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:120)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:129)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:277)&#13;
	at com.indus.pratice.basics.TestModulo.testModuloSer1(TestModulo.java:28)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testModuloSer2" classname="com.indus.pratice.basics.TestModulo" time="0.0">
      <failure>junit.framework.AssertionFailedError: expected:&lt;2.0&gt; but was:&lt;0.0&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:86)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:246)&#13;
	at com.indus.pratice.basics.TestModulo.testModuloSer2(TestModulo.java:40)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
