<?xml version="1.0" encoding="UTF-8"?><testrun name="TestDivision" project="BasicProgram" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.indus.pratice.basics.TestDivision" time="0.002">
    <testcase name="warning" classname="junit.framework.TestSuite.1" time="0.002">
      <failure>junit.framework.AssertionFailedError: No tests found in com.indus.pratice.basics.TestDivision&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.TestCase.fail(TestCase.java:223)&#13;
	at junit.framework.TestSuite$1.runTest(TestSuite.java:96)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
